CREATE TABLE "PUBLIC"."PIO"
(
   ID bigint DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_303F17F0_6FC8_4FA8_BC56_8EBFDB7955F6) NOT NULL,
   USERNAME varchar(50),
   CONTEUDO varchar(255),
   DATACRIACAO timestamp
)
;
CREATE TABLE "PUBLIC"."SEGUIDORES"
(
   ID bigint PRIMARY KEY NOT NULL,
   USUARIO_ID bigint,
   SEGUIDOR_ID bigint
)
;
CREATE TABLE "PUBLIC"."USUARIO"
(
   USERNAME varchar(50),
   PASSWORD varchar(50),
   NOME varchar(50),
   SOBRENOME varchar(50),
   EMAIL varchar(50),
   ID bigint PRIMARY KEY NOT NULL
)
;
ALTER TABLE "PUBLIC"."SEGUIDORES"
ADD CONSTRAINT CONSTRAINT_A9
FOREIGN KEY (USUARIO_ID)
REFERENCES "PUBLIC"."USUARIO"(ID)
;
ALTER TABLE "PUBLIC"."SEGUIDORES"
ADD CONSTRAINT CONSTRAINT_A9B
FOREIGN KEY (SEGUIDOR_ID)
REFERENCES "PUBLIC"."USUARIO"(ID)
;
CREATE INDEX CONSTRAINT_INDEX_A ON "PUBLIC"."SEGUIDORES"(USUARIO_ID)
;
CREATE INDEX CONSTRAINT_INDEX_A9 ON "PUBLIC"."SEGUIDORES"(SEGUIDOR_ID)
;
CREATE UNIQUE INDEX PRIMARY_KEY_A ON "PUBLIC"."SEGUIDORES"(ID)
;
CREATE UNIQUE INDEX PRIMARY_KEY_2 ON "PUBLIC"."USUARIO"(ID)
;
